[functions.create-mp-preference]
verify_jwt = false

[functions.submit-order]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.payment-status]
verify_jwt = false

[functions.verify-inventory-admin]
verify_jwt = false

[functions.update-price]
verify_jwt = false

[functions.add-product]
verify_jwt = false

[functions.submit-ticket]
verify_jwt = false

[functions.setup-tickets-table]
verify_jwt = false

[functions.get-nil-likeness]
verify_jwt = false

[functions.get-inventory]
verify_jwt = false
